# Generated by Django 4.2 on 2026-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_id_alter_videolike_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
